// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: agent/agent.proto

package agent

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AgentServiceService defines service.
type AgentServiceService interface {
	CreateAgent(ctx context.Context, req *CreateAgentRequest) (*CreateAgentResponse, error)

	GetAgent(ctx context.Context, req *GetAgentRequest) (*GetAgentResponse, error)

	UpdateAgent(ctx context.Context, req *UpdateAgentRequest) (*UpdateAgentResponse, error)

	DeleteAgent(ctx context.Context, req *DeleteAgentRequest) (*DeleteAgentResponse, error)

	ExecuteAgent(ctx context.Context, req *ExecuteAgentRequest) (*ExecuteAgentResponse, error)
}

func AgentServiceService_CreateAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServiceService).CreateAgent(ctx, reqbody.(*CreateAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServiceService_GetAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServiceService).GetAgent(ctx, reqbody.(*GetAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServiceService_UpdateAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServiceService).UpdateAgent(ctx, reqbody.(*UpdateAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServiceService_DeleteAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServiceService).DeleteAgent(ctx, reqbody.(*DeleteAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServiceService_ExecuteAgent_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ExecuteAgentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServiceService).ExecuteAgent(ctx, reqbody.(*ExecuteAgentRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AgentServiceServer_ServiceDesc descriptor for server.RegisterService.
var AgentServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.elysia.chat_agent.agent.AgentService",
	HandlerType: ((*AgentServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.elysia.chat_agent.agent.AgentService/CreateAgent",
			Func: AgentServiceService_CreateAgent_Handler,
		},
		{
			Name: "/trpc.elysia.chat_agent.agent.AgentService/GetAgent",
			Func: AgentServiceService_GetAgent_Handler,
		},
		{
			Name: "/trpc.elysia.chat_agent.agent.AgentService/UpdateAgent",
			Func: AgentServiceService_UpdateAgent_Handler,
		},
		{
			Name: "/trpc.elysia.chat_agent.agent.AgentService/DeleteAgent",
			Func: AgentServiceService_DeleteAgent_Handler,
		},
		{
			Name: "/trpc.elysia.chat_agent.agent.AgentService/ExecuteAgent",
			Func: AgentServiceService_ExecuteAgent_Handler,
		},
	},
}

// RegisterAgentServiceService registers service.
func RegisterAgentServiceService(s server.Service, svr AgentServiceService) {
	if err := s.Register(&AgentServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AgentService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAgentService struct{}

func (s *UnimplementedAgentService) CreateAgent(ctx context.Context, req *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, errors.New("rpc CreateAgent of service AgentService is not implemented")
}
func (s *UnimplementedAgentService) GetAgent(ctx context.Context, req *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, errors.New("rpc GetAgent of service AgentService is not implemented")
}
func (s *UnimplementedAgentService) UpdateAgent(ctx context.Context, req *UpdateAgentRequest) (*UpdateAgentResponse, error) {
	return nil, errors.New("rpc UpdateAgent of service AgentService is not implemented")
}
func (s *UnimplementedAgentService) DeleteAgent(ctx context.Context, req *DeleteAgentRequest) (*DeleteAgentResponse, error) {
	return nil, errors.New("rpc DeleteAgent of service AgentService is not implemented")
}
func (s *UnimplementedAgentService) ExecuteAgent(ctx context.Context, req *ExecuteAgentRequest) (*ExecuteAgentResponse, error) {
	return nil, errors.New("rpc ExecuteAgent of service AgentService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AgentServiceClientProxy defines service client proxy
type AgentServiceClientProxy interface {
	CreateAgent(ctx context.Context, req *CreateAgentRequest, opts ...client.Option) (rsp *CreateAgentResponse, err error)

	GetAgent(ctx context.Context, req *GetAgentRequest, opts ...client.Option) (rsp *GetAgentResponse, err error)

	UpdateAgent(ctx context.Context, req *UpdateAgentRequest, opts ...client.Option) (rsp *UpdateAgentResponse, err error)

	DeleteAgent(ctx context.Context, req *DeleteAgentRequest, opts ...client.Option) (rsp *DeleteAgentResponse, err error)

	ExecuteAgent(ctx context.Context, req *ExecuteAgentRequest, opts ...client.Option) (rsp *ExecuteAgentResponse, err error)
}

type AgentServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAgentServiceClientProxy = func(opts ...client.Option) AgentServiceClientProxy {
	return &AgentServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AgentServiceClientProxyImpl) CreateAgent(ctx context.Context, req *CreateAgentRequest, opts ...client.Option) (*CreateAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.chat_agent.agent.AgentService/CreateAgent")
	msg.WithCalleeServiceName(AgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentService")
	msg.WithCalleeMethod("CreateAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServiceClientProxyImpl) GetAgent(ctx context.Context, req *GetAgentRequest, opts ...client.Option) (*GetAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.chat_agent.agent.AgentService/GetAgent")
	msg.WithCalleeServiceName(AgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentService")
	msg.WithCalleeMethod("GetAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServiceClientProxyImpl) UpdateAgent(ctx context.Context, req *UpdateAgentRequest, opts ...client.Option) (*UpdateAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.chat_agent.agent.AgentService/UpdateAgent")
	msg.WithCalleeServiceName(AgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentService")
	msg.WithCalleeMethod("UpdateAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServiceClientProxyImpl) DeleteAgent(ctx context.Context, req *DeleteAgentRequest, opts ...client.Option) (*DeleteAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.chat_agent.agent.AgentService/DeleteAgent")
	msg.WithCalleeServiceName(AgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentService")
	msg.WithCalleeMethod("DeleteAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServiceClientProxyImpl) ExecuteAgent(ctx context.Context, req *ExecuteAgentRequest, opts ...client.Option) (*ExecuteAgentResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.elysia.chat_agent.agent.AgentService/ExecuteAgent")
	msg.WithCalleeServiceName(AgentServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentService")
	msg.WithCalleeMethod("ExecuteAgent")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ExecuteAgentResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
